window.TieJieAdConfig={
  testBuild:true,
  rewardedGold:'',
  rewardedChicken:'',
  rewardedFruit:'',
  rewardedRevive:'',
  rewardedStageDouble:'',
  rewardedTemporaryRecruit:'',
  interstitialStage:''
};
