(() => {
  'use strict';
  const STORAGE_KEY='tiejie-language-v1';
  const languages={
    'zh-Hans':'简体中文','zh-Hant':'繁體中文',en:'English',ja:'日本語',ko:'한국어',es:'Español',pt:'Português',fr:'Français',de:'Deutsch',ru:'Русский',
  };
  const zh={
    gameTitle:'避难所格斗',tagline:'先试手感，再决定长线内容。',start:'进入黑钢城',continueStage:'继续第 {stage} 关',levelSelect:'选择关卡',recruit:'招募队友',skills:'技能',leaderboard:'闯关排行榜',feedback:'意见反馈',settings:'设置',back:'← 返回',save:'保存',cancel:'取消',close:'关闭',language:'界面语言',playerName:'角色名字',playerNameHint:'1–12个文字、数字、空格或下划线',settingsTitle:'游戏设置',settingsSub:'语言、角色名与本机选项',rankTitle:'闯关排行榜',rankSub:'服务器最高通关前十名',rankLoading:'正在读取排行榜……',rankEmpty:'暂时还没有排行记录',rankStage:'最高关',rankStats:'属性',rankSkills:'技能',feedbackTitle:'意见反馈',feedbackSub:'问题会提交到测试服务器',feedbackType:'反馈类型',feedbackBug:'游戏问题',feedbackIdea:'玩法建议',feedbackOther:'其他',feedbackContent:'反馈内容',feedbackHint:'请描述发生了什么、所在关卡和复现步骤（10–800字）',feedbackSubmit:'提交反馈',feedbackSending:'正在提交……',feedbackSent:'反馈已提交，感谢你的帮助',feedbackTooShort:'请至少填写10个字',feedbackFailed:'提交失败，请稍后重试',nameInvalid:'名字需为1–12个文字、数字、空格或下划线',nameSaved:'角色名字已保存',syncing:'正在同步服务器进度……',synced:'服务器进度已同步',offline:'当前离线，进度会保存在本机',login:'登录',register:'注册并进入',username:'用户名（3–24位）',password:'密码（至少8位）',authPrompt:'请登录已有账号，或注册一个新账号',audio:'音乐与音效',vibration:'震动反馈',on:'开',off:'关',resume:'继续战斗',endRun:'结束本局',menu:'菜单',growth:'强化',punch:'拳',grab:'抓',jump:'跳',kick:'腿',stage:'关',hp:'血量',atk:'力量',def:'防御',noSkills:'无',retry:'重新验证',
  };
  const packs={
    'zh-Hans':zh,
    'zh-Hant':{...zh,gameTitle:'避難所格鬥',tagline:'先試手感，再決定長線內容。',start:'進入黑鋼城',levelSelect:'選擇關卡',recruit:'招募隊友',skills:'技能',leaderboard:'闖關排行榜',feedback:'意見回饋',settings:'設定',save:'儲存',language:'介面語言',playerName:'角色名稱',settingsTitle:'遊戲設定',settingsSub:'語言、角色名稱與本機選項',rankTitle:'闖關排行榜',rankSub:'伺服器最高通關前十名',rankLoading:'正在讀取排行榜……',rankEmpty:'暫時還沒有排行記錄',feedbackTitle:'意見回饋',feedbackSubmit:'提交回饋',nameSaved:'角色名稱已儲存',syncing:'正在同步伺服器進度……',synced:'伺服器進度已同步',offline:'目前離線，進度會儲存在本機',register:'註冊並進入',audio:'音樂與音效',vibration:'震動回饋',resume:'繼續戰鬥',endRun:'結束本局',menu:'選單',growth:'強化'},
    en:{gameTitle:'Shelter Combat',tagline:'Try the combat first. Decide the long journey later.',start:'Enter Blacksteel City',continueStage:'Continue Stage {stage}',levelSelect:'Select Stage',recruit:'Recruit Ally',skills:'Skills',leaderboard:'Leaderboard',feedback:'Feedback',settings:'Settings',back:'← Back',save:'Save',cancel:'Cancel',close:'Close',language:'Language',playerName:'Fighter Name',playerNameHint:'1–12 letters, numbers, spaces or underscores',settingsTitle:'Settings',settingsSub:'Language, fighter name and device options',rankTitle:'Leaderboard',rankSub:'Top 10 highest stages on the server',rankLoading:'Loading leaderboard…',rankEmpty:'No ranking records yet',rankStage:'Best',rankStats:'Stats',rankSkills:'Skills',feedbackTitle:'Feedback',feedbackSub:'Your report is sent to the test server',feedbackType:'Category',feedbackBug:'Bug',feedbackIdea:'Suggestion',feedbackOther:'Other',feedbackContent:'Details',feedbackHint:'Describe what happened, the stage and reproduction steps (10–800 characters)',feedbackSubmit:'Submit Feedback',feedbackSending:'Sending…',feedbackSent:'Feedback submitted. Thank you!',feedbackTooShort:'Please enter at least 10 characters',feedbackFailed:'Submission failed. Please try again later.',nameInvalid:'Name must be 1–12 letters, numbers, spaces or underscores',nameSaved:'Fighter name saved',syncing:'Syncing server progress…',synced:'Server progress synced',offline:'Offline. Progress is saved on this device.',login:'Log In',register:'Register & Enter',username:'Username (3–24 characters)',password:'Password (at least 8 characters)',authPrompt:'Log in or register a new account',audio:'Music & SFX',vibration:'Vibration',on:'On',off:'Off',resume:'Resume',endRun:'End Run',menu:'Menu',growth:'Upgrade',punch:'Punch',grab:'Grab',jump:'Jump',kick:'Kick',stage:'Stage',hp:'HP',atk:'Power',def:'Defense',noSkills:'None',retry:'Retry'},
    ja:{gameTitle:'シェルター格闘',tagline:'まず操作感を試し、その先を決めよう。',start:'黒鋼城へ',levelSelect:'ステージ選択',recruit:'仲間を募集',skills:'スキル',leaderboard:'ランキング',feedback:'フィードバック',settings:'設定',back:'← 戻る',save:'保存',cancel:'キャンセル',language:'表示言語',playerName:'キャラクター名',settingsTitle:'ゲーム設定',settingsSub:'言語・名前・端末設定',rankTitle:'ランキング',rankSub:'サーバー最高到達ステージ TOP 10',rankLoading:'ランキングを読み込み中…',rankEmpty:'ランキング記録はまだありません',rankStage:'最高',rankStats:'能力',rankSkills:'スキル',feedbackTitle:'フィードバック',feedbackSubmit:'送信',feedbackSent:'送信しました。ありがとうございます',nameSaved:'名前を保存しました',audio:'音楽・効果音',vibration:'振動',on:'オン',off:'オフ',resume:'戦闘を続ける',endRun:'終了',menu:'メニュー',growth:'強化',punch:'拳',grab:'掴',jump:'跳',kick:'脚',hp:'体力',atk:'攻撃',def:'防御',noSkills:'なし'},
    ko:{gameTitle:'대피소 격투',tagline:'전투 감각을 먼저 확인해 보세요.',start:'흑강성 입장',levelSelect:'스테이지 선택',recruit:'동료 모집',skills:'스킬',leaderboard:'랭킹',feedback:'의견 보내기',settings:'설정',back:'← 뒤로',save:'저장',cancel:'취소',language:'언어',playerName:'캐릭터 이름',settingsTitle:'게임 설정',rankTitle:'랭킹',rankSub:'서버 최고 스테이지 TOP 10',rankLoading:'랭킹 불러오는 중…',rankEmpty:'랭킹 기록이 없습니다',rankStage:'최고',rankStats:'능력치',rankSkills:'스킬',feedbackTitle:'의견 보내기',feedbackSubmit:'제출',feedbackSent:'제출되었습니다. 감사합니다',nameSaved:'이름을 저장했습니다',audio:'음악 및 효과음',vibration:'진동',on:'켜기',off:'끄기',resume:'계속하기',endRun:'게임 종료',menu:'메뉴',growth:'강화',punch:'주먹',grab:'잡기',jump:'점프',kick:'발차기',hp:'체력',atk:'공격',def:'방어',noSkills:'없음'},
    es:{gameTitle:'Combate del Refugio',tagline:'Prueba el combate antes de decidir tu viaje.',start:'Entrar en Ciudad Acero',levelSelect:'Elegir nivel',recruit:'Reclutar aliado',skills:'Habilidades',leaderboard:'Clasificación',feedback:'Comentarios',settings:'Ajustes',back:'← Volver',save:'Guardar',cancel:'Cancelar',language:'Idioma',playerName:'Nombre del luchador',settingsTitle:'Ajustes del juego',rankTitle:'Clasificación',rankSub:'Los 10 niveles máximos del servidor',rankLoading:'Cargando…',rankEmpty:'Aún no hay registros',rankStage:'Máximo',rankStats:'Atributos',rankSkills:'Habilidades',feedbackTitle:'Comentarios',feedbackSubmit:'Enviar',feedbackSent:'Enviado. ¡Gracias!',nameSaved:'Nombre guardado',audio:'Música y efectos',vibration:'Vibración',on:'Sí',off:'No',resume:'Continuar',endRun:'Terminar partida',menu:'Menú',growth:'Mejorar',punch:'Puño',grab:'Agarre',jump:'Salto',kick:'Patada',hp:'Vida',atk:'Fuerza',def:'Defensa',noSkills:'Ninguna'},
    pt:{gameTitle:'Combate do Abrigo',tagline:'Experimente o combate antes de seguir a jornada.',start:'Entrar na Cidade Aço',levelSelect:'Selecionar fase',recruit:'Recrutar aliado',skills:'Habilidades',leaderboard:'Ranking',feedback:'Feedback',settings:'Configurações',back:'← Voltar',save:'Salvar',cancel:'Cancelar',language:'Idioma',playerName:'Nome do lutador',settingsTitle:'Configurações do jogo',rankTitle:'Ranking',rankSub:'Top 10 maiores fases do servidor',rankLoading:'Carregando…',rankEmpty:'Ainda não há registros',rankStage:'Recorde',rankStats:'Atributos',rankSkills:'Habilidades',feedbackTitle:'Feedback',feedbackSubmit:'Enviar',feedbackSent:'Enviado. Obrigado!',nameSaved:'Nome salvo',audio:'Música e efeitos',vibration:'Vibração',on:'Ligado',off:'Desligado',resume:'Continuar',endRun:'Encerrar partida',menu:'Menu',growth:'Melhorar',punch:'Soco',grab:'Agarrar',jump:'Pular',kick:'Chute',hp:'Vida',atk:'Força',def:'Defesa',noSkills:'Nenhuma'},
    fr:{gameTitle:'Combat du Refuge',tagline:'Testez le combat avant de poursuivre l’aventure.',start:'Entrer dans Cité Acier',levelSelect:'Choisir un niveau',recruit:'Recruter un allié',skills:'Compétences',leaderboard:'Classement',feedback:'Commentaires',settings:'Paramètres',back:'← Retour',save:'Enregistrer',cancel:'Annuler',language:'Langue',playerName:'Nom du combattant',settingsTitle:'Paramètres du jeu',rankTitle:'Classement',rankSub:'Top 10 des niveaux atteints',rankLoading:'Chargement…',rankEmpty:'Aucun classement',rankStage:'Record',rankStats:'Attributs',rankSkills:'Compétences',feedbackTitle:'Commentaires',feedbackSubmit:'Envoyer',feedbackSent:'Envoyé. Merci !',nameSaved:'Nom enregistré',audio:'Musique et effets',vibration:'Vibration',on:'Oui',off:'Non',resume:'Continuer',endRun:'Terminer',menu:'Menu',growth:'Améliorer',punch:'Poing',grab:'Saisie',jump:'Saut',kick:'Pied',hp:'PV',atk:'Force',def:'Défense',noSkills:'Aucune'},
    de:{gameTitle:'Bunkerkampf',tagline:'Teste zuerst das Kampfsystem.',start:'Schwarzstahlstadt betreten',levelSelect:'Level wählen',recruit:'Verbündeten anwerben',skills:'Fähigkeiten',leaderboard:'Rangliste',feedback:'Feedback',settings:'Einstellungen',back:'← Zurück',save:'Speichern',cancel:'Abbrechen',language:'Sprache',playerName:'Kämpfername',settingsTitle:'Spieleinstellungen',rankTitle:'Rangliste',rankSub:'Top 10 der höchsten Level',rankLoading:'Wird geladen…',rankEmpty:'Noch keine Einträge',rankStage:'Bestwert',rankStats:'Werte',rankSkills:'Fähigkeiten',feedbackTitle:'Feedback',feedbackSubmit:'Senden',feedbackSent:'Gesendet. Danke!',nameSaved:'Name gespeichert',audio:'Musik & Effekte',vibration:'Vibration',on:'An',off:'Aus',resume:'Fortsetzen',endRun:'Lauf beenden',menu:'Menü',growth:'Verbessern',punch:'Faust',grab:'Greifen',jump:'Sprung',kick:'Tritt',hp:'LP',atk:'Kraft',def:'Abwehr',noSkills:'Keine'},
    ru:{gameTitle:'Бой в убежище',tagline:'Сначала испытайте боевую систему.',start:'Войти в город Чёрной стали',levelSelect:'Выбор этапа',recruit:'Нанять союзника',skills:'Навыки',leaderboard:'Рейтинг',feedback:'Обратная связь',settings:'Настройки',back:'← Назад',save:'Сохранить',cancel:'Отмена',language:'Язык',playerName:'Имя бойца',settingsTitle:'Настройки игры',rankTitle:'Рейтинг',rankSub:'10 лучших результатов сервера',rankLoading:'Загрузка…',rankEmpty:'Записей пока нет',rankStage:'Рекорд',rankStats:'Параметры',rankSkills:'Навыки',feedbackTitle:'Обратная связь',feedbackSubmit:'Отправить',feedbackSent:'Отправлено. Спасибо!',nameSaved:'Имя сохранено',audio:'Музыка и звуки',vibration:'Вибрация',on:'Вкл.',off:'Выкл.',resume:'Продолжить',endRun:'Завершить',menu:'Меню',growth:'Усилить',punch:'Удар',grab:'Захват',jump:'Прыжок',kick:'Пинок',hp:'Здоровье',atk:'Сила',def:'Защита',noSkills:'Нет'},
  };
  Object.assign(packs['zh-Hans'],{authTitle:'铁街测试通行证',authChecking:'正在验证测试资格……',authPrompt:'请登录已有账号，或注册一个新账号',authVerifying:'正在验证账号……',authCreating:'正在创建账号……',authLoggingIn:'正在登录……',authNetwork:'无法连接账号服务器，请检查网络后重试',authUnconfigured:'账号服务器尚未配置，请联系管理员',authFoot:'测试期间开放注册；正式上线后测试账号会统一清除'});
  Object.assign(packs['zh-Hant'],{authTitle:'鐵街測試通行證',authChecking:'正在驗證測試資格……',authPrompt:'請登入已有帳號，或註冊新帳號',authVerifying:'正在驗證帳號……',authCreating:'正在建立帳號……',authLoggingIn:'正在登入……',authNetwork:'無法連線帳號伺服器，請檢查網路後重試',authUnconfigured:'帳號伺服器尚未設定',authFoot:'測試期間開放註冊；正式上線後測試帳號會統一清除'});
  Object.assign(packs.en,{authTitle:'Iron Street Test Pass',authChecking:'Checking test access…',authPrompt:'Log in or register a new account',authVerifying:'Verifying account…',authCreating:'Creating account…',authLoggingIn:'Logging in…',authNetwork:'Cannot reach the account server. Check your connection and retry.',authUnconfigured:'The account server is not configured.',authFoot:'Registration is open during testing. Test accounts will be removed before release.'});
  Object.assign(packs['zh-Hans'],{deleteAccountTitle:'删除账号',deleteAccountHint:'永久删除账号、游戏进度、排行榜和反馈记录，此操作无法恢复。',deleteAccount:'删除我的账号',deleteAccountWarning:'账号及全部服务器游戏数据将永久删除。请输入当前密码确认。',currentPassword:'当前密码',deleteAccountConfirm:'永久删除',deleteAccountDeleting:'正在验证并删除……',deleteAccountWrongPassword:'当前密码错误',deleteAccountFailed:'删除失败，请稍后重试'});
  Object.assign(packs['zh-Hant'],{deleteAccountTitle:'刪除帳號',deleteAccountHint:'永久刪除帳號、遊戲進度、排行榜和意見記錄，此操作無法復原。',deleteAccount:'刪除我的帳號',deleteAccountWarning:'帳號及全部伺服器遊戲資料將永久刪除。請輸入目前密碼確認。',currentPassword:'目前密碼',deleteAccountConfirm:'永久刪除',deleteAccountDeleting:'正在驗證並刪除……',deleteAccountWrongPassword:'目前密碼錯誤',deleteAccountFailed:'刪除失敗，請稍後重試'});
  Object.assign(packs.en,{deleteAccountTitle:'Delete account',deleteAccountHint:'Permanently delete your account, game progress, leaderboard entry, and feedback. This cannot be undone.',deleteAccount:'Delete my account',deleteAccountWarning:'Your account and all server game data will be permanently deleted. Enter your current password to confirm.',currentPassword:'Current password',deleteAccountConfirm:'Delete permanently',deleteAccountDeleting:'Verifying and deleting…',deleteAccountWrongPassword:'Current password is incorrect',deleteAccountFailed:'Could not delete the account. Try again later.'});
  Object.assign(packs['zh-Hans'],{resetGauntlet:'重置关卡'});
  Object.assign(packs['zh-Hant'],{resetGauntlet:'重置關卡'});
  Object.assign(packs.en,{resetGauntlet:'Reset Stage'});
  const aliases={zh:'zh-Hans','zh-cn':'zh-Hans','zh-sg':'zh-Hans','zh-tw':'zh-Hant','zh-hk':'zh-Hant','zh-mo':'zh-Hant',en:'en',ja:'ja',ko:'ko',es:'es',pt:'pt',fr:'fr',de:'de',ru:'ru'};
  function detect(){for(const item of navigator.languages||[navigator.language]){const value=String(item||'').toLowerCase(),exact=aliases[value],base=aliases[value.split('-')[0]];if(exact||base)return exact||base}return'zh-Hans'}
  let current='';try{current=localStorage.getItem(STORAGE_KEY)||''}catch{}if(!languages[current])current=detect();
  function t(key,vars={}){const value=packs[current]?.[key]??packs.en?.[key]??zh[key]??key;return String(value).replace(/\{(\w+)\}/g,(_,name)=>vars[name]??'')}
  const textBindings={
    '#start':'start','#level-select':'levelSelect','#recruit-btn':'recruit','#skill-btn':'skills','#rank-btn':'leaderboard','#feedback-btn':'feedback','#settings-btn':'settings','#auth-login':'login','#auth-register':'register','#auth-retry':'retry','#battle-menu-resume':'resume','#battle-menu-end':'endRun','[data-action="punch"]':'punch','[data-action="grab"]':'grab','[data-action="jump"]':'jump','[data-action="kick"]':'kick',
  };
  function apply(root=document){document.documentElement.lang=current;for(const [selector,key]of Object.entries(textBindings)){const node=root.querySelector?.(selector);if(node)node.textContent=t(key)}root.querySelectorAll?.('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));root.querySelectorAll?.('[data-i18n-placeholder]').forEach(node=>node.placeholder=t(node.dataset.i18nPlaceholder));root.querySelectorAll?.('[data-i18n-aria]').forEach(node=>node.setAttribute('aria-label',t(node.dataset.i18nAria)));root.querySelectorAll?.('[data-i18n-title]').forEach(node=>node.title=t(node.dataset.i18nTitle))}
  function setLanguage(value){if(!languages[value])return false;current=value;try{localStorage.setItem(STORAGE_KEY,value)}catch{}apply();window.dispatchEvent(new CustomEvent('tiejie-language-changed',{detail:{language:value}}));return true}
  window.TieJieI18n=Object.freeze({languages,t,get language(){return current},setLanguage,apply});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(),{once:true});else apply();
})();
